version: '4.19'
services:
  employeeDB:
    container_name: employeeDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeeDB
  paymentDB:
    container_name: paymentDB
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - paymentDB:/data/db/paymentDB

volumes:
  employeeDB:
  paymentDB:
  rabbitmq_data:
