version: '4.19'
services:
  employeeDB:
    container_name: employeeDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeeDB

volumes:
  employeeDB:
